### ISSUE TITLE
You sayed you needed something with speed?

### ISSUE THREAD

**Issue by frank-dspeed** [crussell52/node-socket-ipc#5]
Your Implamentation can't be fast even with the most do able optimization in JS
you should use "zeromq" if you need speed 

your transcoder alone is out of performance view a bottleneck

**Comment by crussell52** [comment]
@frank-dspeed Thank you for the feedback -- "fast" is a relative term, I guess.  Generally speaking, socket files are a pretty darn fast way to pass messages around.  Understandably, binding to a lower level library (as is done in `zeromq`) has speed benefits.

What I like in particular about zeromq is the wide language support -- in fact, there is a lot to like about using zeromq. I will definitely add it to the list of other options (my whole intro needs to be trimmed back significantly, anyway; seemed like a good idea at the time, but now it is just seems noisy 😬).

For now, the simplicity offered here is a fair trade-off for my purposes and perhaps for others.

**Comment by frank-dspeed** [comment]
@crussell52 add only nanomsg to the list of alternatives its a succesor of zeromq and also offers websockets and posix sockets like your implamentation its install able via npm "nanomsg"

cheers and greetings it was not a insult it was only a rugh way to say the truth that no one should talk about speed when using the JSVM that is written in C :)

**Comment by crussell52** [comment]
@frank-dspeed No worries!  I'm all about knowledge sharing 😄 That's why we open-source, right?

Re: nanomsg... That space is a little confusing, tbh -- it looks like there is also nng which is a successor to nanomsg (which is a successor to zeromq).  But `nng` does not appear to have a nodejs binding available? The nanomsg binding is definitely better documented than the zeromg one... In any case, I will add a note as soon as I can about nanomsg, but zeromq seems like it is still in use by many -- maybe even more readily available for cross-language messages (?) so I might leave the mention there.

To your original point about the `transcoder` being a bottleneck -- it might be interesting to see a transcoding implementation that binds to a c implementation.  Is that in your wheelhouse? I imagine it as a separate npm package, rather than a direct contribution but that might be really nifty.

You also seem to have some experience/knowledge in this area, so if you wanted to make a doc contribution which quantifies the speed of this package in a meaningful way, that would be _amazing_. I can say that my initial tests achieved something like 10k (smallish) msgs per second. -- I didn't really push it too hard, just enough to see that it was plenty fast for my purposes.  Also didn't feel it was a thorough enough range of tests to post results as the documentation.

**Comment by frank-dspeed** [comment]
@crussell52 nanomsg is the current succesor and is only a little bit diffrent then zeromq to make a long story short i followed all blog posts of the creators of nanomsg and zeromq and can save make the conclusion only nanomsg matters and nanomsg is also cross system it even supports more protocols like WS for websockets and posix compatible .socket files for linux and pipes for windows overall nanomsg and its node or go bindings or any other bindings is what you would want to use today :D

**Comment by frank-dspeed** [comment]
@crussell52 nanomsg is the current succesor and is only a little bit diffrent then zeromq to make a long story short i followed all blog posts of the creators of nanomsg and zeromq and can save make the conclusion only nanomsg matters and nanomsg is also cross system it even supports more protocols like WS for websockets and posix compatible .socket files for linux and pipes for windows overall nanomsg and its node or go bindings or any other bindings is what you would want to use today :D
